### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by SkrytnayaRediska** [ZenyaBelkov/Homework_lesson8#2]
https://github.com/ZenyaBelkov/Homework_lesson8/blob/136deebf4cadd745721d83da466258e3dbdd58b2/homework/homework_lesson8.py#L124C5-L124C10

This is also complicated. You can create smth kinda switch-case and use just this code part for user choices instead of a large number of calls to this function, which are dispersed throughout the code

**Comment by ZenyaBelkov** [comment]
https://github.com/ZenyaBelkov/Homework_lesson8/tree/1-solution
